/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * A single exit-node client. `start()` connects and registers; a background
 * supervisor then keeps the connection up until `stop()`.
 */
export declare class ProxyClient {
  constructor(options: ProxyClientOptions)
  /**
   * Connect to a gateway and start serving proxy requests. Resolves once
   * registered; rejects if no gateway accepts within `startTimeoutMs`.
   */
  start(): Promise<void>
  /** Close the connection and stop reconnecting. */
  stop(): Promise<void>
  get connected(): boolean
  get gatewayId(): string | null
  /** The gateway-assigned `account:instance-id`, or `null` until connected. */
  get clientKey(): string | null
  /**
   * Why the gateway last refused this client, or `null` if it has not since
   * the last successful connection.
   */
  get lastRejection(): string | null
  /**
   * Tell the gateway which transport the host is on now: "cellular",
   * "wifi", "ethernet" or "other"; `null` when unknown. The gateway uses
   * it, with the network it measures, to classify the exit as mobile,
   * residential or datacenter.
   */
  setNetwork(network?: string | undefined | null): void
  /** The transport last reported, or `null`. */
  get network(): string | null
  /** One of `idle`, `connecting`, `connected`, `stopped`. */
  get state(): string
}

/**
 * Options for [`ProxyClient`]. In production a host passes only `publisherId`;
 * the gateway address and CA are development overrides.
 */
export interface ProxyClientOptions {
  /**
   * The public publisher id (an identifier, not a secret) the gateway resolves
   * to the earning account.
   */
  publisherId: string
  /** Gateway `host:port` addresses, tried in rotation. */
  gatewayAddresses: Array<string>
  /**
   * PEM file pinning the gateway CA (for a self-signed dev gateway). Omit in
   * production to verify the gateway's public cert against the system roots.
   * Ignored when `caCertPem` is set.
   */
  caCertPath?: string
  /** PEM bytes of the gateway CA (an alternative to a file path). */
  caCertPem?: Uint8Array
  /** How long `start()` waits for the first connection. Default 30000. */
  startTimeoutMs?: number
  /** How long the exit waits when dialling a target. Default 15000. */
  connectTimeoutMs?: number
  /**
   * Stable id for this machine, if the host keeps one. The SDK never mints or
   * stores it — only the host knows where an id belongs on its platform.
   * Omit to stay anonymous in the dashboard.
   */
  deviceId?: string
  /**
   * A human name for this machine, conventionally its hostname. Seeds the
   * dashboard label.
   */
  deviceName?: string
  /**
   * The host application, e.g. "my-app/2.1.0". Distinct from the SDK version,
   * which the SDK reports itself.
   */
  app?: string
  /**
   * The transport the host is on at start: "cellular", "wifi", "ethernet"
   * or "other". Report later changes with `setNetwork`.
   */
  network?: string
}
