# frozen_string_literal: true

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .rb file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Ruby
# helpers directly inline like we're doing here.

require 'ffi'

module Meerkly
  def self.uniffi_in_range(i, type_name, min, max)
    raise TypeError, "no implicit conversion of #{i} into Integer" unless i.respond_to?(:to_int)

    i = i.to_int
    raise RangeError, "#{type_name} requires #{min} <= value < #{max}" unless min <= i && i < max

    i
  end

  def self.uniffi_utf8(v)
    raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)

    v = v.to_str.encode(Encoding::UTF_8)
    raise Encoding::InvalidByteSequenceError, 'not a valid UTF-8 encoded string' unless v.valid_encoding?

    v
  end

  def self.uniffi_bytes(v)
    raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)

    v.to_str
  end

  class RustBuffer < FFI::Struct
    layout :capacity, :uint64,
           :len,      :uint64,
           :data,     :pointer

    def self.alloc(size)
      Meerkly.rust_call(:ffi_meerkly_rustbuffer_alloc, size)
    end

    def self.reserve(rbuf, additional)
      Meerkly.rust_call(:ffi_meerkly_rustbuffer_reserve, rbuf, additional)
    end

    def free
      Meerkly.rust_call(:ffi_meerkly_rustbuffer_free, self)
    end

    def capacity
      self[:capacity]
    end

    def len
      self[:len]
    end

    def len=(value)
      self[:len] = value
    end

    def data
      self[:data]
    end

    def to_s
      "RustBuffer(capacity=#{capacity}, len=#{len}, data=#{data.read_bytes len})"
    end

    # The allocated buffer will be automatically freed if an error occurs, ensuring that
    # we don't accidentally leak it.
    def self.allocWithBuilder
      builder = RustBufferBuilder.new

      begin
        yield builder
      rescue StandardError => e
        builder.discard
        raise e
      end
    end

    # The RustBuffer will be freed once the context-manager exits, ensuring that we don't
    # leak it even if an error occurs.
    def consumeWithStream
      stream = RustBufferStream.new self

      yield stream

      raise 'junk data left in buffer after consuming' if stream.remaining != 0
    ensure
      free
    end

    def self.allocFromString(value)
      RustBuffer.allocWithBuilder do |builder|
        builder.write value.encode('utf-8')
        return builder.finalize
      end
    end

    def consumeIntoString
      consumeWithStream do |stream|
        return stream.read(stream.remaining).force_encoding(Encoding::UTF_8)
      end
    end

    # The primitive Bytes type.

    def self.allocFromBytes(value)
      RustBuffer.allocWithBuilder do |builder|
        builder.write_Bytes(value)
        return builder.finalize
      end
    end

    def consumeIntoBytes
      consumeWithStream do |stream|
        return stream.readBytes
      end
    end

    # The Record type ProxyConfig.

    def self.check_lower_TypeProxyConfig(v)
      RustBuffer.check_lower_Sequencestring(v.gateway_addresses)
      RustBuffer.check_lower_Optionalstring(v.ca_cert_path)
      RustBuffer.check_lower_Optionalbytes(v.ca_cert_pem)
      RustBuffer.check_lower_Optionalu32(v.start_timeout_ms)
      RustBuffer.check_lower_Optionalu32(v.connect_timeout_ms)
      RustBuffer.check_lower_Optionalstring(v.device_id)
      RustBuffer.check_lower_Optionalstring(v.device_name)
      RustBuffer.check_lower_Optionalstring(v.sdk)
      RustBuffer.check_lower_Optionalstring(v.app)
      RustBuffer.check_lower_Optionalstring(v.network)
    end

    def self.alloc_from_TypeProxyConfig(v)
      RustBuffer.allocWithBuilder do |builder|
        builder.write_TypeProxyConfig(v)
        return builder.finalize
      end
    end

    def consumeIntoTypeProxyConfig
      consumeWithStream do |stream|
        return stream.readTypeProxyConfig
      end
    end

    # The Enum type ClientState.

    def self.check_lower_TypeClientState(v); end

    def self.alloc_from_TypeClientState(v)
      RustBuffer.allocWithBuilder do |builder|
        builder.write_TypeClientState(v)
        return builder.finalize
      end
    end

    def consumeIntoTypeClientState
      consumeWithStream do |stream|
        return stream.readTypeClientState
      end
    end

    # The Optional<T> type for u32.

    def self.check_lower_Optionalu32(v)
      nil if v.nil?
    end

    def self.alloc_from_Optionalu32(v)
      RustBuffer.allocWithBuilder do |builder|
        builder.write_Optionalu32(v)
        return builder.finalize
      end
    end

    def consumeIntoOptionalu32
      consumeWithStream do |stream|
        return stream.readOptionalu32
      end
    end

    # The Optional<T> type for string.

    def self.check_lower_Optionalstring(v)
      nil if v.nil?
    end

    def self.alloc_from_Optionalstring(v)
      RustBuffer.allocWithBuilder do |builder|
        builder.write_Optionalstring(v)
        return builder.finalize
      end
    end

    def consumeIntoOptionalstring
      consumeWithStream do |stream|
        return stream.readOptionalstring
      end
    end

    # The Optional<T> type for bytes.

    def self.check_lower_Optionalbytes(v)
      nil if v.nil?
    end

    def self.alloc_from_Optionalbytes(v)
      RustBuffer.allocWithBuilder do |builder|
        builder.write_Optionalbytes(v)
        return builder.finalize
      end
    end

    def consumeIntoOptionalbytes
      consumeWithStream do |stream|
        return stream.readOptionalbytes
      end
    end

    # The Sequence<T> type for string.

    def self.check_lower_Sequencestring(v)
      v.each do |item|
      end
    end

    def self.alloc_from_Sequencestring(v)
      RustBuffer.allocWithBuilder do |builder|
        builder.write_Sequencestring(v)
        return builder.finalize
      end
    end

    def consumeIntoSequencestring
      consumeWithStream do |stream|
        return stream.readSequencestring
      end
    end
  end

  module UniFFILib
    class ForeignBytes < FFI::Struct
      layout :len,      :int32,
             :data,     :pointer

      def len
        self[:len]
      end

      def data
        self[:data]
      end

      def to_s
        "ForeignBytes(len=#{len}, data=#{data.read_bytes(len)})"
      end
    end
  end

  private_constant :UniFFILib

  # Helper for structured reading of values from a RustBuffer.
  class RustBufferStream
    def initialize(rbuf)
      @rbuf = rbuf
      @offset = 0
    end

    def remaining
      @rbuf.len - @offset
    end

    def read(size)
      raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

      data = @rbuf.data.get_bytes @offset, size

      @offset += size

      data
    end

    def readU32
      unpack_from 4, 'L>'
    end

    def readBool
      v = unpack_from 1, 'c'

      return false if v.zero?
      return true if v == 1

      raise InternalError, 'Unexpected byte for Boolean type'
    end

    def readString
      size = unpack_from 4, 'l>'

      raise InternalError, 'Unexpected negative string length' if size.negative?

      read(size).force_encoding(Encoding::UTF_8)
    end

    def readBytes
      size = unpack_from 4, 'l>'

      raise InternalError, 'Unexpected negative byte string length' if size.negative?

      read(size).force_encoding(Encoding::BINARY)
    end

    # The Object type ProxyClient.

    def readTypeProxyClient
      pointer = FFI::Pointer.new unpack_from 8, 'Q>'
      ProxyClient.uniffi_allocate(pointer)
    end

    # The Record type ProxyConfig.

    def readTypeProxyConfig
      ProxyConfig.new(
        publisher_id: readString,
        gateway_addresses: readSequencestring,
        ca_cert_path: readOptionalstring,
        ca_cert_pem: readOptionalbytes,
        start_timeout_ms: readOptionalu32,
        connect_timeout_ms: readOptionalu32,
        device_id: readOptionalstring,
        device_name: readOptionalstring,
        sdk: readOptionalstring,
        app: readOptionalstring,
        network: readOptionalstring
      )
    end

    # The Enum type ClientState.

    def readTypeClientState
      variant = unpack_from 4, 'l>'

      return ClientState::IDLE if variant == 1
      return ClientState::CONNECTING if variant == 2
      return ClientState::CONNECTED if variant == 3
      return ClientState::STOPPED if variant == 4

      raise InternalError, 'Unexpected variant tag for TypeClientState'
    end

    # The Error type ProxyError

    def readTypeProxyError
      variant = unpack_from 4, 'l>'

      if variant == 1
        return ProxyError::Failed.new(
          readString
        )
      end

      raise InternalError, 'Unexpected variant tag for TypeProxyError'
    end

    # The Optional<T> type for u32.

    def readOptionalu32
      flag = unpack_from 1, 'c'

      if flag.zero?
        nil
      elsif flag == 1
        readU32
      else
        raise InternalError, 'Unexpected flag byte for Optionalu32'
      end
    end

    # The Optional<T> type for string.

    def readOptionalstring
      flag = unpack_from 1, 'c'

      if flag.zero?
        nil
      elsif flag == 1
        readString
      else
        raise InternalError, 'Unexpected flag byte for Optionalstring'
      end
    end

    # The Optional<T> type for bytes.

    def readOptionalbytes
      flag = unpack_from 1, 'c'

      if flag.zero?
        nil
      elsif flag == 1
        readBytes
      else
        raise InternalError, 'Unexpected flag byte for Optionalbytes'
      end
    end

    # The Sequence<T> type for string.

    def readSequencestring
      count = unpack_from 4, 'l>'

      raise InternalError, 'Unexpected negative sequence length' if count.negative?

      items = []

      count.times do
        items.append readString
      end

      items
    end

    def unpack_from(size, format)
      raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

      value = @rbuf.data.get_bytes(@offset, size).unpack format

      @offset += size

      # TODO: verify this
      raise 'more than one element!!!' if value.size > 1

      value[0]
    end
  end

  private_constant :RustBufferStream

  # Helper for structured writing of values into a RustBuffer.
  class RustBufferBuilder
    def initialize
      @rust_buf = RustBuffer.alloc 16
      @rust_buf.len = 0
    end

    def finalize
      rbuf = @rust_buf

      @rust_buf = nil

      rbuf
    end

    def discard
      return if @rust_buf.nil?

      rbuf = finalize
      rbuf.free
    end

    def write(value)
      reserve(value.bytes.size) do
        @rust_buf.data.put_array_of_char @rust_buf.len, value.bytes
      end
    end

    def write_U32(v)
      v = Meerkly.uniffi_in_range(v, 'u32', 0, 2**32)
      pack_into(4, 'L>', v)
    end

    def write_Bool(v)
      pack_into(1, 'c', v ? 1 : 0)
    end

    def write_String(v)
      v = Meerkly.uniffi_utf8(v)
      pack_into 4, 'l>', v.bytes.size
      write v
    end

    def write_Bytes(v)
      v = Meerkly.uniffi_bytes(v)
      pack_into 4, 'l>', v.bytes.size
      write v
    end

    # The Object type ProxyClient.

    def write_TypeProxyClient(obj)
      pointer = ProxyClient.uniffi_lower obj
      pack_into(8, 'Q>', pointer.address)
    end

    # The Record type ProxyConfig.

    def write_TypeProxyConfig(v)
      write_String(v.publisher_id)
      write_Sequencestring(v.gateway_addresses)
      write_Optionalstring(v.ca_cert_path)
      write_Optionalbytes(v.ca_cert_pem)
      write_Optionalu32(v.start_timeout_ms)
      write_Optionalu32(v.connect_timeout_ms)
      write_Optionalstring(v.device_id)
      write_Optionalstring(v.device_name)
      write_Optionalstring(v.sdk)
      write_Optionalstring(v.app)
      write_Optionalstring(v.network)
    end

    # The Enum type ClientState.

    def write_TypeClientState(v)
      pack_into(4, 'l>', v)
    end

    # The Optional<T> type for u32.

    def write_Optionalu32(v)
      if v.nil?
        pack_into(1, 'c', 0)
      else
        pack_into(1, 'c', 1)
        write_U32(v)
      end
    end

    # The Optional<T> type for string.

    def write_Optionalstring(v)
      if v.nil?
        pack_into(1, 'c', 0)
      else
        pack_into(1, 'c', 1)
        write_String(v)
      end
    end

    # The Optional<T> type for bytes.

    def write_Optionalbytes(v)
      if v.nil?
        pack_into(1, 'c', 0)
      else
        pack_into(1, 'c', 1)
        write_Bytes(v)
      end
    end

    # The Sequence<T> type for string.

    def write_Sequencestring(items)
      pack_into(4, 'l>', items.size)

      items.each do |item|
        write_String(item)
      end
    end

    private

    def reserve(num_bytes)
      @rust_buf = RustBuffer.reserve(@rust_buf, num_bytes) if @rust_buf.len + num_bytes > @rust_buf.capacity

      yield

      @rust_buf.len += num_bytes
    end

    def pack_into(size, format, value)
      reserve(size) do
        @rust_buf.data.put_array_of_char @rust_buf.len, [value].pack(format).bytes
      end
    end
  end

  private_constant :RustBufferBuilder

  # Error definitions
  class RustCallStatus < FFI::Struct
    layout :code, :int8,
           :error_buf, RustBuffer

    def code
      self[:code]
    end

    def error_buf
      self[:error_buf]
    end

    def to_s
      "RustCallStatus(code=#{self[:code]})"
    end
  end

  # These match the values from the uniffi::rustcalls module
  CALL_SUCCESS = 0
  CALL_ERROR = 1
  CALL_PANIC = 2

  module ProxyError
    class Failed < StandardError
      def initialize(reason)
        @reason = reason
        super()
      end

      attr_reader :reason

      def to_s
        "#{self.class.name}(reason=#{@reason.inspect})"
      end
    end
  end

  # Map error modules to the RustBuffer method name that reads them
  ERROR_MODULE_TO_READER_METHOD = {

    ProxyError => :readTypeProxyError

  }.freeze

  private_constant :ERROR_MODULE_TO_READER_METHOD, :CALL_SUCCESS, :CALL_ERROR, :CALL_PANIC,
                   :RustCallStatus

  def self.consume_buffer_into_error(error_module, rust_buffer)
    rust_buffer.consumeWithStream do |stream|
      reader_method = ERROR_MODULE_TO_READER_METHOD[error_module]
      return stream.send(reader_method)
    end
  end

  class InternalError < StandardError
  end

  def self.rust_call(fn_name, *args)
    # Call a rust function
    rust_call_with_error(nil, fn_name, *args)
  end

  def self.rust_call_with_error(error_module, fn_name, *args)
    # Call a rust function and handle errors
    #
    # Use this when the rust function returns a Result<>.  error_module must be the error_module that corresponds to that Result.

    # NOTE: RustCallStatus.new zeroes out the struct, which is exactly what we
    # want to pass to Rust (code=0, error_buf=RustBuffer(len=0, capacity=0,
    # data=NULL))
    status = RustCallStatus.new
    args << status

    result = UniFFILib.public_send(fn_name, *args)

    case status.code
    when CALL_SUCCESS
      result
    when CALL_ERROR
      raise consume_buffer_into_error(error_module, status.error_buf) unless error_module.nil?

      status.error_buf.free
      raise InternalError, 'CALL_ERROR with no error_module set'

    when CALL_PANIC
      # When the rust code sees a panic, it tries to construct a RustBuffer
      # with the message.  But if that code panics, then it just sends back
      # an empty buffer.
      raise InternalError, status.error_buf.consumeIntoString if status.error_buf.len.positive?

      raise InternalError, 'Rust panic'

    else
      raise InternalError, "Unknown call status: #{status.code}"
    end
  end

  private_class_method :consume_buffer_into_error

  # This is how we find and load the dynamic library provided by the component.
  # For now we just look it up by name.
  module UniFFILib
    extend FFI::Library

    ffi_lib 'meerkly'

    attach_function :uniffi_meerkly_fn_clone_proxyclient,
                    [:pointer, RustCallStatus.by_ref],
                    :pointer
    attach_function :uniffi_meerkly_fn_free_proxyclient,
                    [:pointer, RustCallStatus.by_ref],
                    :void
    attach_function :uniffi_meerkly_fn_constructor_proxyclient_new,
                    [RustBuffer.by_value, RustCallStatus.by_ref],
                    :pointer
    attach_function :uniffi_meerkly_fn_method_proxyclient_client_key,
                    [:pointer, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :uniffi_meerkly_fn_method_proxyclient_connected,
                    [:pointer, RustCallStatus.by_ref],
                    :int8
    attach_function :uniffi_meerkly_fn_method_proxyclient_gateway_id,
                    [:pointer, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :uniffi_meerkly_fn_method_proxyclient_last_rejection,
                    [:pointer, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :uniffi_meerkly_fn_method_proxyclient_network,
                    [:pointer, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :uniffi_meerkly_fn_method_proxyclient_set_network,
                    [:pointer, RustBuffer.by_value, RustCallStatus.by_ref],
                    :void
    attach_function :uniffi_meerkly_fn_method_proxyclient_start,
                    [:pointer, RustCallStatus.by_ref],
                    :uint64
    attach_function :uniffi_meerkly_fn_method_proxyclient_start_blocking,
                    [:pointer, RustCallStatus.by_ref],
                    :void
    attach_function :uniffi_meerkly_fn_method_proxyclient_state,
                    [:pointer, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :uniffi_meerkly_fn_method_proxyclient_stop,
                    [:pointer, RustCallStatus.by_ref],
                    :uint64
    attach_function :uniffi_meerkly_fn_method_proxyclient_stop_blocking,
                    [:pointer, RustCallStatus.by_ref],
                    :void
    attach_function :ffi_meerkly_rustbuffer_alloc,
                    [:uint64, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :ffi_meerkly_rustbuffer_from_bytes,
                    [ForeignBytes, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :ffi_meerkly_rustbuffer_free,
                    [RustBuffer.by_value, RustCallStatus.by_ref],
                    :void
    attach_function :ffi_meerkly_rustbuffer_reserve,
                    [RustBuffer.by_value, :uint64, RustCallStatus.by_ref],
                    RustBuffer.by_value
    attach_function :uniffi_meerkly_checksum_method_proxyclient_client_key,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_connected,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_gateway_id,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_last_rejection,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_network,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_set_network,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_start,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_start_blocking,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_state,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_stop,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_method_proxyclient_stop_blocking,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :uniffi_meerkly_checksum_constructor_proxyclient_new,
                    [RustCallStatus.by_ref],
                    :uint16
    attach_function :ffi_meerkly_uniffi_contract_version,
                    [RustCallStatus.by_ref],
                    :uint32
  end

  # Public interface members begin here.

  class ClientState
    IDLE = 1
    CONNECTING = 2
    CONNECTED = 3
    STOPPED = 4
  end

  # Record type ProxyConfig
  class ProxyConfig
    attr_reader :publisher_id, :gateway_addresses, :ca_cert_path, :ca_cert_pem, :start_timeout_ms, :connect_timeout_ms,
                :device_id, :device_name, :sdk, :app, :network

    def initialize(publisher_id:, gateway_addresses:, ca_cert_path: nil, ca_cert_pem: nil, start_timeout_ms: nil,
                   connect_timeout_ms: nil, device_id: nil, device_name: nil, sdk: nil, app: nil, network: nil)
      @publisher_id = publisher_id
      @gateway_addresses = gateway_addresses
      @ca_cert_path = ca_cert_path
      @ca_cert_pem = ca_cert_pem
      @start_timeout_ms = start_timeout_ms
      @connect_timeout_ms = connect_timeout_ms
      @device_id = device_id
      @device_name = device_name
      @sdk = sdk
      @app = app
      @network = network
    end

    def ==(other)
      return false if @publisher_id != other.publisher_id
      return false if @gateway_addresses != other.gateway_addresses
      return false if @ca_cert_path != other.ca_cert_path
      return false if @ca_cert_pem != other.ca_cert_pem
      return false if @start_timeout_ms != other.start_timeout_ms
      return false if @connect_timeout_ms != other.connect_timeout_ms
      return false if @device_id != other.device_id
      return false if @device_name != other.device_name
      return false if @sdk != other.sdk
      return false if @app != other.app
      return false if @network != other.network

      true
    end
  end

  class ProxyClient
    # A private helper for initializing instances of the class from a raw pointer,
    # bypassing any initialization logic and ensuring they are GC'd properly.
    def self.uniffi_allocate(pointer)
      pointer.autorelease = false
      inst = allocate
      inst.instance_variable_set :@pointer, pointer
      ObjectSpace.define_finalizer(inst, uniffi_define_finalizer_by_pointer(pointer, inst.object_id))
      inst
    end

    # A private helper for registering an object finalizer.
    # N.B. it's important that this does not capture a reference
    # to the actual instance, only its underlying pointer.
    def self.uniffi_define_finalizer_by_pointer(pointer, _object_id)
      proc do |_id|
        Meerkly.rust_call(
          :uniffi_meerkly_fn_free_proxyclient,
          pointer
        )
      end
    end

    # A private helper for lowering instances into a raw pointer.
    # This does an explicit typecheck, because accidentally lowering a different type of
    # object in a place where this type is expected, could lead to memory unsafety.
    def self.uniffi_check_lower(inst)
      return if inst.is_a? self

      raise TypeError, "Expected a ProxyClient instance, got #{inst}"
    end

    def uniffi_clone_pointer
      Meerkly.rust_call(
        :uniffi_meerkly_fn_clone_proxyclient,
        @pointer
      )
    end

    def self.uniffi_lower(inst)
      inst.uniffi_clone_pointer
    end

    def initialize(config)
      config = config
      RustBuffer.check_lower_TypeProxyConfig(config)
      pointer = Meerkly.rust_call_with_error(ProxyError, :uniffi_meerkly_fn_constructor_proxyclient_new,
                                             RustBuffer.alloc_from_TypeProxyConfig(config))
      @pointer = pointer
      ObjectSpace.define_finalizer(self, self.class.uniffi_define_finalizer_by_pointer(pointer, object_id))
    end

    def client_key
      result = Meerkly.rust_call(:uniffi_meerkly_fn_method_proxyclient_client_key, uniffi_clone_pointer)
      result.consumeIntoOptionalstring
    end

    def connected
      result = Meerkly.rust_call(:uniffi_meerkly_fn_method_proxyclient_connected, uniffi_clone_pointer)
      result == 1
    end

    def gateway_id
      result = Meerkly.rust_call(:uniffi_meerkly_fn_method_proxyclient_gateway_id, uniffi_clone_pointer)
      result.consumeIntoOptionalstring
    end

    def last_rejection
      result = Meerkly.rust_call(:uniffi_meerkly_fn_method_proxyclient_last_rejection, uniffi_clone_pointer)
      result.consumeIntoOptionalstring
    end

    def network
      result = Meerkly.rust_call(:uniffi_meerkly_fn_method_proxyclient_network, uniffi_clone_pointer)
      result.consumeIntoOptionalstring
    end

    def set_network(network)
      network = (network ? Meerkly.uniffi_utf8(network) : nil)
      RustBuffer.check_lower_Optionalstring(network)
      Meerkly.rust_call(:uniffi_meerkly_fn_method_proxyclient_set_network, uniffi_clone_pointer,
                        RustBuffer.alloc_from_Optionalstring(network))
    end

    def start
      Meerkly.rust_call_with_error(ProxyError, :uniffi_meerkly_fn_method_proxyclient_start, uniffi_clone_pointer)
    end

    def start_blocking
      Meerkly.rust_call_with_error(ProxyError, :uniffi_meerkly_fn_method_proxyclient_start_blocking,
                                   uniffi_clone_pointer)
    end

    def state
      result = Meerkly.rust_call(:uniffi_meerkly_fn_method_proxyclient_state, uniffi_clone_pointer)
      result.consumeIntoTypeClientState
    end

    def stop
      Meerkly.rust_call_with_error(ProxyError, :uniffi_meerkly_fn_method_proxyclient_stop, uniffi_clone_pointer)
    end

    def stop_blocking
      Meerkly.rust_call_with_error(ProxyError, :uniffi_meerkly_fn_method_proxyclient_stop_blocking,
                                   uniffi_clone_pointer)
    end
  end
end
