// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(meerklyFFI)
import meerklyFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_meerkly_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_meerkly_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A single exit-node client. `start()` connects and registers; a background
 * supervisor keeps the connection up until `stop()`. Stores nothing itself —
 * a device id, if the host keeps one, is passed in and only carried.
 */
public protocol ProxyClientProtocol : AnyObject {
    
    /**
     * The gateway-assigned `account:instance-id`, or null until connected.
     */
    func clientKey()  -> String?
    
    func connected()  -> Bool
    
    func gatewayId()  -> String?
    
    /**
     * Why the gateway last refused this client (e.g. "another device is
     * already connected from this IP address"), or null if it has not since
     * the last successful connection. Meant to be shown to the user while the
     * client keeps retrying.
     */
    func lastRejection()  -> String?
    
    /**
     * The transport last reported, or null.
     */
    func network()  -> String?
    
    /**
     * Tell the gateway which transport the host is on now: "cellular",
     * "wifi", "ethernet" or "other"; null when unknown. Call it whenever the
     * platform reports a change (on Android, a `ConnectivityManager`
     * callback). The gateway uses it, with the network it measures, to
     * classify the exit as mobile, residential or datacenter.
     */
    func setNetwork(network: String?) 
    
    /**
     * Connect and register. Resolves once online; errors on timeout.
     */
    func start() async throws 
    
    /**
     * Blocking `start`, for bindings without async support (e.g. Ruby). Blocks
     * the caller until connected (or the start timeout).
     */
    func startBlocking() throws 
    
    func state()  -> ClientState
    
    /**
     * Close the connection and stop reconnecting.
     */
    func stop() async throws 
    
    /**
     * Blocking `stop`.
     */
    func stopBlocking() throws 
    
}

/**
 * A single exit-node client. `start()` connects and registers; a background
 * supervisor keeps the connection up until `stop()`. Stores nothing itself —
 * a device id, if the host keeps one, is passed in and only carried.
 */
open class ProxyClient:
    ProxyClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_meerkly_fn_clone_proxyclient(self.pointer, $0) }
    }
public convenience init(config: ProxyConfig)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeProxyError.lift) {
    uniffi_meerkly_fn_constructor_proxyclient_new(
        FfiConverterTypeProxyConfig.lower(config),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_meerkly_fn_free_proxyclient(pointer, $0) }
    }

    

    
    /**
     * The gateway-assigned `account:instance-id`, or null until connected.
     */
open func clientKey() -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_meerkly_fn_method_proxyclient_client_key(self.uniffiClonePointer(),$0
    )
})
}
    
open func connected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_meerkly_fn_method_proxyclient_connected(self.uniffiClonePointer(),$0
    )
})
}
    
open func gatewayId() -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_meerkly_fn_method_proxyclient_gateway_id(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Why the gateway last refused this client (e.g. "another device is
     * already connected from this IP address"), or null if it has not since
     * the last successful connection. Meant to be shown to the user while the
     * client keeps retrying.
     */
open func lastRejection() -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_meerkly_fn_method_proxyclient_last_rejection(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The transport last reported, or null.
     */
open func network() -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_meerkly_fn_method_proxyclient_network(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Tell the gateway which transport the host is on now: "cellular",
     * "wifi", "ethernet" or "other"; null when unknown. Call it whenever the
     * platform reports a change (on Android, a `ConnectivityManager`
     * callback). The gateway uses it, with the network it measures, to
     * classify the exit as mobile, residential or datacenter.
     */
open func setNetwork(network: String?) {try! rustCall() {
    uniffi_meerkly_fn_method_proxyclient_set_network(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(network),$0
    )
}
}
    
    /**
     * Connect and register. Resolves once online; errors on timeout.
     */
open func start()async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_meerkly_fn_method_proxyclient_start(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_meerkly_rust_future_poll_void,
            completeFunc: ffi_meerkly_rust_future_complete_void,
            freeFunc: ffi_meerkly_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeProxyError.lift
        )
}
    
    /**
     * Blocking `start`, for bindings without async support (e.g. Ruby). Blocks
     * the caller until connected (or the start timeout).
     */
open func startBlocking()throws  {try rustCallWithError(FfiConverterTypeProxyError.lift) {
    uniffi_meerkly_fn_method_proxyclient_start_blocking(self.uniffiClonePointer(),$0
    )
}
}
    
open func state() -> ClientState {
    return try!  FfiConverterTypeClientState.lift(try! rustCall() {
    uniffi_meerkly_fn_method_proxyclient_state(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Close the connection and stop reconnecting.
     */
open func stop()async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_meerkly_fn_method_proxyclient_stop(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_meerkly_rust_future_poll_void,
            completeFunc: ffi_meerkly_rust_future_complete_void,
            freeFunc: ffi_meerkly_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeProxyError.lift
        )
}
    
    /**
     * Blocking `stop`.
     */
open func stopBlocking()throws  {try rustCallWithError(FfiConverterTypeProxyError.lift) {
    uniffi_meerkly_fn_method_proxyclient_stop_blocking(self.uniffiClonePointer(),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProxyClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ProxyClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ProxyClient {
        return ProxyClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ProxyClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProxyClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ProxyClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProxyClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> ProxyClient {
    return try FfiConverterTypeProxyClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProxyClient_lower(_ value: ProxyClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeProxyClient.lower(value)
}


/**
 * Options for [`ProxyClient::new`]. In production a host passes only
 * `publisherId`; the gateway address and CA are development overrides.
 */
public struct ProxyConfig {
    public var publisherId: String
    public var gatewayAddresses: [String]
    public var caCertPath: String?
    public var caCertPem: Data?
    public var startTimeoutMs: UInt32?
    public var connectTimeoutMs: UInt32?
    /**
     * Stable id for this machine, if the host keeps one. The SDK never mints or
     * stores it — only the host knows where an id belongs on its platform.
     */
    public var deviceId: String?
    /**
     * A human name for this machine, conventionally its hostname.
     */
    public var deviceName: String?
    /**
     * Which binding is calling: "python", "ruby", "go", "swift", "kotlin".
     * Unlike the node binding, this crate cannot detect it — uniffi generates
     * all five from this one crate — so a host that wants its language
     * attributed correctly sets it here. Defaults to the SDK's own default.
     */
    public var sdk: String?
    /**
     * The host application, e.g. "my-app/2.1.0".
     */
    public var app: String?
    /**
     * The transport the host is on at start: "cellular", "wifi", "ethernet"
     * or "other". Report later changes with `set_network`.
     */
    public var network: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(publisherId: String, gatewayAddresses: [String], caCertPath: String? = nil, caCertPem: Data? = nil, startTimeoutMs: UInt32? = nil, connectTimeoutMs: UInt32? = nil, 
        /**
         * Stable id for this machine, if the host keeps one. The SDK never mints or
         * stores it — only the host knows where an id belongs on its platform.
         */deviceId: String? = nil, 
        /**
         * A human name for this machine, conventionally its hostname.
         */deviceName: String? = nil, 
        /**
         * Which binding is calling: "python", "ruby", "go", "swift", "kotlin".
         * Unlike the node binding, this crate cannot detect it — uniffi generates
         * all five from this one crate — so a host that wants its language
         * attributed correctly sets it here. Defaults to the SDK's own default.
         */sdk: String? = nil, 
        /**
         * The host application, e.g. "my-app/2.1.0".
         */app: String? = nil, 
        /**
         * The transport the host is on at start: "cellular", "wifi", "ethernet"
         * or "other". Report later changes with `set_network`.
         */network: String? = nil) {
        self.publisherId = publisherId
        self.gatewayAddresses = gatewayAddresses
        self.caCertPath = caCertPath
        self.caCertPem = caCertPem
        self.startTimeoutMs = startTimeoutMs
        self.connectTimeoutMs = connectTimeoutMs
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.sdk = sdk
        self.app = app
        self.network = network
    }
}



extension ProxyConfig: Equatable, Hashable {
    public static func ==(lhs: ProxyConfig, rhs: ProxyConfig) -> Bool {
        if lhs.publisherId != rhs.publisherId {
            return false
        }
        if lhs.gatewayAddresses != rhs.gatewayAddresses {
            return false
        }
        if lhs.caCertPath != rhs.caCertPath {
            return false
        }
        if lhs.caCertPem != rhs.caCertPem {
            return false
        }
        if lhs.startTimeoutMs != rhs.startTimeoutMs {
            return false
        }
        if lhs.connectTimeoutMs != rhs.connectTimeoutMs {
            return false
        }
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.deviceName != rhs.deviceName {
            return false
        }
        if lhs.sdk != rhs.sdk {
            return false
        }
        if lhs.app != rhs.app {
            return false
        }
        if lhs.network != rhs.network {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(publisherId)
        hasher.combine(gatewayAddresses)
        hasher.combine(caCertPath)
        hasher.combine(caCertPem)
        hasher.combine(startTimeoutMs)
        hasher.combine(connectTimeoutMs)
        hasher.combine(deviceId)
        hasher.combine(deviceName)
        hasher.combine(sdk)
        hasher.combine(app)
        hasher.combine(network)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProxyConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProxyConfig {
        return
            try ProxyConfig(
                publisherId: FfiConverterString.read(from: &buf), 
                gatewayAddresses: FfiConverterSequenceString.read(from: &buf), 
                caCertPath: FfiConverterOptionString.read(from: &buf), 
                caCertPem: FfiConverterOptionData.read(from: &buf), 
                startTimeoutMs: FfiConverterOptionUInt32.read(from: &buf), 
                connectTimeoutMs: FfiConverterOptionUInt32.read(from: &buf), 
                deviceId: FfiConverterOptionString.read(from: &buf), 
                deviceName: FfiConverterOptionString.read(from: &buf), 
                sdk: FfiConverterOptionString.read(from: &buf), 
                app: FfiConverterOptionString.read(from: &buf), 
                network: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ProxyConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.publisherId, into: &buf)
        FfiConverterSequenceString.write(value.gatewayAddresses, into: &buf)
        FfiConverterOptionString.write(value.caCertPath, into: &buf)
        FfiConverterOptionData.write(value.caCertPem, into: &buf)
        FfiConverterOptionUInt32.write(value.startTimeoutMs, into: &buf)
        FfiConverterOptionUInt32.write(value.connectTimeoutMs, into: &buf)
        FfiConverterOptionString.write(value.deviceId, into: &buf)
        FfiConverterOptionString.write(value.deviceName, into: &buf)
        FfiConverterOptionString.write(value.sdk, into: &buf)
        FfiConverterOptionString.write(value.app, into: &buf)
        FfiConverterOptionString.write(value.network, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProxyConfig_lift(_ buf: RustBuffer) throws -> ProxyConfig {
    return try FfiConverterTypeProxyConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProxyConfig_lower(_ value: ProxyConfig) -> RustBuffer {
    return FfiConverterTypeProxyConfig.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * What the client is currently doing.
 */

public enum ClientState {
    
    case idle
    case connecting
    case connected
    case stopped
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientState: FfiConverterRustBuffer {
    typealias SwiftType = ClientState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .idle
        
        case 2: return .connecting
        
        case 3: return .connected
        
        case 4: return .stopped
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ClientState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .idle:
            writeInt(&buf, Int32(1))
        
        
        case .connecting:
            writeInt(&buf, Int32(2))
        
        
        case .connected:
            writeInt(&buf, Int32(3))
        
        
        case .stopped:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientState_lift(_ buf: RustBuffer) throws -> ClientState {
    return try FfiConverterTypeClientState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientState_lower(_ value: ClientState) -> RustBuffer {
    return FfiConverterTypeClientState.lower(value)
}



extension ClientState: Equatable, Hashable {}




/**
 * The single error every fallible SDK call returns.
 *
 * The field is `reason`, not `message`, and that is not a style choice. uniffi
 * generates the Kotlin variant as a subclass of `kotlin.Exception` with an
 * `override val message`, so a field literally named `message` collides with
 * `Throwable.message` and the generated Kotlin does not compile. Upstream's
 * answer is to not name an error field `message`. Nothing else reads the name,
 * and Kotlin callers still get the text through `e.message` as usual.
 */
public enum ProxyError {

    
    
    case Failed(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProxyError: FfiConverterRustBuffer {
    typealias SwiftType = ProxyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProxyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Failed(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ProxyError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Failed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


extension ProxyError: Equatable, Hashable {}

extension ProxyError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_meerkly_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_client_key() != 43031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_connected() != 17032) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_gateway_id() != 12787) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_last_rejection() != 11660) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_network() != 13252) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_set_network() != 38512) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_start() != 7497) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_start_blocking() != 15227) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_state() != 22483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_stop() != 34296) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_method_proxyclient_stop_blocking() != 58714) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_meerkly_checksum_constructor_proxyclient_new() != 23512) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all